import { Color, ColorScheme, ColorValue } from "./types.js";

export const COLORS = [
  "NO_COLOR",
  "BLACK",
  "RED",
  "GREEN",
  "BROWN",
  "YELLOW",
  "BLUE",
  "PURPLE",
  "CYAN",
  "WHITE",
] as const;

export const COLOR_VALUES = [
  "\x1b[0m",
  "\x1b[1;30m",
  "\x1b[1;31m",
  "\x1b[1;32m",
  "\x1b[1;33m",
  "\x1b[1;33m",
  "\x1b[1;34m",
  "\x1b[1;35m",
  "\x1b[1;36m",
  "\x1b[1;37m",
] as const;

export const COLOR_VALUES_MAP: Record<Color, ColorValue> = {
  NO_COLOR: "\x1b[0m",
  BLACK: "\x1b[1;30m",
  RED: "\x1b[1;31m",
  GREEN: "\x1b[1;32m",
  BROWN: "\x1b[1;33m",
  YELLOW: "\x1b[1;33m",
  BLUE: "\x1b[1;34m",
  PURPLE: "\x1b[1;35m",
  CYAN: "\x1b[1;36m",
  WHITE: "\x1b[1;37m",
};

export const DEFAULT_COLOR_SCHEME: ColorScheme = {
  GET: "GREEN",
  get: "GREEN",
  POST: "RED",
  post: "RED",
  PUT: "PURPLE",
  put: "PURPLE",
  PATCH: "BLUE",
  patch: "BLUE",
  OPTIONS: "CYAN",
  options: "CYAN",
  DELETE: "YELLOW",
  delete: "YELLOW",
  HEAD: "NO_COLOR",
  head: "NO_COLOR",
  PROPFIND: "NO_COLOR",
  PROPPATCH: "NO_COLOR",
  MKCOL: "NO_COLOR",
  COPY: "NO_COLOR",
  MOVE: "NO_COLOR",
  LOCK: "NO_COLOR",
  UNLOCK: "NO_COLOR",
  TRACE: "NO_COLOR",
  SEARCH: "NO_COLOR",
  REPORT: "NO_COLOR",
  MKCALENDAR: "NO_COLOR",
  propfind: "NO_COLOR",
  proppatch: "NO_COLOR",
  mkcol: "NO_COLOR",
  copy: "NO_COLOR",
  move: "NO_COLOR",
  lock: "NO_COLOR",
  unlock: "NO_COLOR",
  trace: "NO_COLOR",
  search: "NO_COLOR",
  report: "NO_COLOR",
  mkcalendar: "NO_COLOR",
};
